/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useLayoutEffect, useMemo, useRef } from "react";
import type * as THREE from "three";
import { MirrorMaterial } from "./MirrorMaterial";
import { MirrorTexture } from "./MirrorTexture";

const baseUrl = import.meta.env.BASE_URL;
export function Road() {
  const { nodes, materials } = useGLTF(baseUrl + "bicycle.glb") as any;

  const matClone = useMemo(() => materials.Road.clone(), [materials.Road]);
  useLayoutEffect(() => () => matClone.dispose(), [matClone]);

  const camera = useThree((state) => state.camera);
  const size = useThree((state) => state.size);

  const mirrorTexture = useMemo(
    () => new MirrorTexture(camera, size),
    [camera],
  );

  const mirrorRef = useRef<THREE.Mesh>(null!);

  useFrame(({ gl, scene, camera }) => {
    mirrorRef.current.visible = false;
    mirrorTexture.render(gl, scene, camera);
    mirrorRef.current.visible = true;
  });

  return (
    <group dispose={null}>
      <mesh
        ref={mirrorRef}
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        renderOrder={1}
      >
        <MirrorMaterial baseMaterial={matClone} renderTexture={mirrorTexture} />
      </mesh>
    </group>
  );
}
