/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

const baseUrl = import.meta.env.BASE_URL;

export function Rail(props: any) {
  const { nodes, materials } = useGLTF(baseUrl + "props.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Esportsm_RailGuard_Ext_13_Dup_42_lambert2_0001.geometry}
        material={materials.lambert2}
        material-roughness={0.2}
      />
    </group>
  );
}
