/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

const baseUrl = import.meta.env.BASE_URL;

export function Sign(props: any) {
  const { nodes, materials } = useGLTF(baseUrl + "props.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface7_Traffic_Signs_0001.geometry}
        material={materials.Traffic_Signs}
        position={[0, 0, 0.263]}
        scale={0.01}
        material-roughness={0.2}
      />
    </group>
  );
}
